config/routes.rb
Ishpage::Engine.routes.draw do
  resources :pages, :path => '/'

end

app/models/ishpage/page.rb
module Ishpage
  class Page < ActiveRecord::Base
  	# This assumes you already have friendly_id in your gemfile and all that good stuff.
  	extend FriendlyId
  	friendly_id :slug, use: :slugged

  	# Fields validation
  	SLUG_REGEX = /\A^[\w&-]+$\Z/

  	validates :title, presence: true,
  	            length: { maximum: 250 }

  	validates :slug, presence: true,
  	            length: { maximum: 250 },
  	            format: SLUG_REGEX
  end
end

app/controllers/ishpage/application_controller.rb
module Ishpage
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/ishpage/pages_controller.rb
require_dependency "ishpage/application_controller"

module Ishpage
  class PagesController < ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    layout 'application'

    # GET /pages
    def index
      @pages = Page.all
    end

    # GET /pages/1
    def show
    end

    # GET /pages/new
    def new
      @page = Page.new
    end

    # GET /pages/1/edit
    def edit
    end

    # POST /pages
    def create
      @page = Page.new(page_params)

      if @page.save
        redirect_to @page, notice: 'Page was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /pages/1
    def update
      if @page.update(page_params)
        redirect_to @page, notice: 'Page was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /pages/1
    def destroy
      @page.destroy
      redirect_to pages_url, notice: 'Page was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_page
        @page = Page.friendly.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def page_params
        params.require(:page).permit(:title, :slug, :content)
      end
  end
end

app/helpers/ishpage/application_helper.rb
module Ishpage
  module ApplicationHelper
  end
end

app/helpers/ishpage/pages_helper.rb
module Ishpage
  module PagesHelper
  end
end

app/views/ishpage/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, { :id => 'title', :class => 'form-control', :placeholder => 'Title' } %>
  </div>
  <div class="field form-group">
    <%= f.label :slug %>
    <%= f.text_field :slug, { :id => 'slug', :class => 'form-control', :placeholder => 'Slug' } %>
  </div>
  <div class="field form-group">
    <%= f.label :content %>
    <%= f.text_area :content, { :id => 'content', :class => 'form-control', :placeholder => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', :rows => 15 } %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/ishpage/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/ishpage/pages/index.html.erb
<% content_for :header do %>
  <h1>Site Pages</h1>
<% end %>

<% if can? :create, Ishpage::Page %>
  <div class="clearfix">
    <p class="pull-right">
      <%= link_to 'New Page', new_page_path, :class => 'btn btn-primary ' %>
    </p>
  </div>
<% end %>


<table class="table table-striped">
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= link_to 'Show', page %></td>
        <% if can? :edit, page %>
          <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <% end %>
        <% if can? :destroy, page %>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ishpage/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/ishpage/pages/show.html.erb
<% content_for :header do %>
	<h1><%= @page.title %></h1>
<% end %>

<div class="clearfix">
	<%= @page.content.html_safe %>
</div>


<% if can? :edit, @page %>
	<div class="clearfix">
		<p class="pull-right">
			<%= link_to 'Edit', edit_page_path(@page), :class => 'btn btn-warning' %>
		</p>
	</div>
<% end %>

app/views/layouts/ishpage/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ishpage</title>
  <%= stylesheet_link_tag    "ishpage/application", media: "all" %>
  <%= javascript_include_tag "ishpage/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>